### PR TITLE
Long press type check

### LINKED ISSUE #19: Long press types not checked
I have set my available long press types to only `.addNew`, but when I long press on a cell as a move it still tries to perform the move long press, and as such the app is crashing. I can see that you check whether the long press types contain `.addNew`, but I don't see `.move` checked anywhere.

Should be fixed by #21

### PR DESCRIPTION
**Pull request by Fawxy**
This fixes #19

### CODE REVIEW

**Comment by zjfjack** [comment]
Hi, Fawxy.

Thanks a lot for your help! 
I've looked through your pull request and you are correct.
But before I approve, I want some changes to your code, could you help me to modify it?
Same file   `JZLongPressWeekView.swift`

1. line 107, change to 
```swift 
public var longPressTypes: [LongPressType] = [LongPressType]()
```
I set a default value to this one because when I was testing and set no longPressTypes, the app will crash.

2. line 350-353, change to 
```swift
let hasItemAtPoint = collectionView.indexPathForItem(at: pointInCollectionView) != nil
        
// Long press should not begin if there are events at long press position and move not required
if hasItemAtPoint && !longPressTypes.contains(LongPressType.move) {
    return false
}
// Long press should not begin if no events at long press position and addNew not required
if !hasItemAtPoint && !longPressTypes.contains(LongPressType.addNew) {
    return false
}
```
I refactored part of your work to make it easier to understand and add comments as well.

Thanks again for helping me to improve this project!

**Comment by Fawxy** [comment]
I've updated the branch :)

**Comment by zjfjack** [comment]
Already merged~
Thanks for your help.
Do you need me release a new pod version to update it?

**Comment by Fawxy** [comment]
I'm installed off my own fork at the moment as I also added in a custom action for long pressing on an event, so that I can present a popover menu rather than the move action, so no worries there.

**Comment by zjfjack** [comment]
Okay.
If you find some other issues, please let me know and make pull requests.
It's wonderful that you can help me for this project.
Thanks

**Pull request merged**
